export enum Allergen {
  NONE = "NONE",
  DAIRY = "DAIRY",
  EGGS = "EGGS",
  PEANUTS = "PEANUTS",
  TREE_NUTS = "TREE_NUTS",
  SOY = "SOY",
  WHEAT = "WHEAT",
  GLUTEN = "GLUTEN",
  FISH = "FISH",
  SHELLFISH = "SHELLFISH",
  SESAME = "SESAME",
  MUSTARD = "MUSTARD",
  CELERY = "CELERY",
  SULFITES = "SULFITES",
  LUPIN = "LUPIN",
  MOLLUSCS = "MOLLUSCS"
}
